version: "3.9"
services:
    ui:
        build:
            context: .
            dockerfile: ./packages/ui/Dockerfile
            args:
                PROJECT_DIR: "${PROJECT_DIR}"
        container_name: ui
        environment: 
            NODE_ENV: "${NODE_ENV}"
            PROJECT_DIR: "${PROJECT_DIR}"
            REACT_APP_SITE_NAME: "${SITE_NAME}"
            REACT_APP_SERVER_ROUTE: "${SERVER_ROUTE}"
            UI_PORT: "${UI_PORT}"
            VIRTUAL_HOST: "${SITE_NAME}"
            VIRTUAL_PORT: "${SERVER_PORT}"
            LETSENCRYPT_HOST: "${SITE_NAME}"
            LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
        ports:
            - 3000:3000
        volumes:
            - ./packages/ui:${PROJECT_DIR}/packages/ui
            - ./packages/shared:${PROJECT_DIR}/packages/shared
            - ./scripts:${PROJECT_DIR}/scripts
        networks:
            - proxy
            - app
        depends_on: 
                - redis
                - db
        command: /bin/sh -c "chmod +x ./scripts/* && ./scripts/ui.sh"
    server:
        build:
            context: .
            dockerfile: ./packages/server/Dockerfile
            args:
                PROJECT_DIR: "${PROJECT_DIR}"
        container_name: server
        environment: 
            NODE_ENV: "${NODE_ENV}"
            JWT_SECRET: "${JWT_SECRET}"
            PROJECT_DIR: "${PROJECT_DIR}"
            DB_HOST: "db"
            DB_PORT: "5432"
            DB_NAME: "${DB_NAME}"
            DB_USER: "${DB_USER}"
            DB_PASSWORD: "${DB_PASSWORD}"
            REDIS_CONN: "${REDIS_CONN}"
            ADMIN_EMAIL: "${ADMIN_EMAIL}"
            ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
            SITE_EMAIL_FROM: "${SITE_EMAIL_FROM}"
            SITE_EMAIL_USERNAME: "${SITE_EMAIL_USERNAME}"
            SITE_EMAIL_PASSWORD: "${SITE_EMAIL_PASSWORD}"
            REACT_APP_SITE_NAME: "${SITE_NAME}"
            REACT_APP_SERVER_ROUTE: "${SERVER_ROUTE}"
            UI_PORT: "${UI_PORT}"
            SERVER_PORT: "${SERVER_PORT}"
            VIRTUAL_HOST: "${SITE_NAME}"
            VIRTUAL_PORT: "${UI_PORT}"
            LETSENCRYPT_HOST: "${SITE_NAME}"
            LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
        ports:
            - 5000:5000
        volumes:
            - ./packages/server:${PROJECT_DIR}/packages/server
            - ./packages/shared:${PROJECT_DIR}/packages/shared
            - ./assets:${PROJECT_DIR}/assets
            - ./scripts:${PROJECT_DIR}/scripts
        networks:
            - proxy
            - app
        depends_on: 
                - redis
                - db
        command: /bin/sh -c "chmod +x ./scripts/* && ./scripts/server.sh"
    db:
        image: postgres:13
        restart: always
        container_name: db
        environment: 
            POSTGRES_DB: "${DB_NAME}"
            POSTGRES_USER: "${DB_USER}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
        ports:
                - 5432:5432
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        networks:
            - app
    # adminer:
    #     image: adminer
    #     restart: always
    #     depends_on: 
    #         - db
    #     ports: 
    #         - 8080:8080
    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379
        networks:
            - app
networks:
    proxy:
        external:
            name: nginx-proxy
    app: