version: "3.9"  # optional since v1.27.0
services:
    db:
        image: postgres:13
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
    redis:
        image: redis
    express:
        image: node:14.17
        depends_on: 
            - db
            - redis
        ports:
            - '5000:5000'
    web:
        build: .
        ports:
        - "5000:5000"
        volumes:
        - .:/code
        - logvolume01:/var/log
        links:
        - redis
    
volumes:
  logvolume01: {}