version: "3.9"
services:
    main:
        build: .
        container_name: nln-main
        environment: 
            NODE_ENV: "${NODE_ENV}"
        ports:
            - '3000:3000'
            - '5000:5000'
        volumes:
            - ./:/srv/app
            - ./packages/server/public:/srv/app/packages/server/public
            - /srv/app/packages/server/private
            - /srv/app/packages/server/images
        depends_on: 
                - redis
                - db
    db:
        build: ./db
        container_name: nln-postgres
        environment: 
            DB_NAME: "${DB_NAME}"
            DB_USER: "${DB_USER}"
            DB_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - pgdata:/var/lib/postgresql/data
    redis:
        image: redis
        container_name: nln-redis
        ports:
            - '6379:6379'
volumes:
    pgdata: