import { TABLES } from "./tables";

// Fields that can be exposed in a query
export const FIELDS = {
    [TABLES.Address]: [
        'id',
        'tag',
        'name',
        'country',
        'administrativeArea',
        'subAdministrativeArea',
        'locality',
        'postalCode',
        'premise',
    ],
    [TABLES.Business]: [
        'id',
        'name',
        'subscribedToNewsletters',
    ],
    [TABLES.Discount]: [
        'id',
        'discount',
        'title',
        'comment',
        'terms',
    ],
    [TABLES.Email]: [
        'id',
        'emailAddress',
        'receivesDeliveryUpdates',
    ],
    [TABLES.Feedback]: [
        'id',
        'text',
    ],
    [TABLES.Image]: [
        'id',
        'extension',
        'alt',
        'description',
        'usedFor',
        'hash',
        'width',
        'height',
    ],
    [TABLES.Order]: [
        'id',
        'status',
        'specialInstructions',
        'desiredDeliveryDate',
        'expectedDeliveryDate',
        'isDelivery',
    ],
    [TABLES.OrderItem]: [
        'id',
        'quantity',
    ],
    [TABLES.Phone]: [
        'id',
        'number',
        'receivesDeliveryUpdates',
    ],
    [TABLES.Plant]: [
        'id',
        'latinName',
        'traitData',
        'imageData',
    ],
    [TABLES.Role]: [
        'id',
        'title',
        'description',
    ],
    [TABLES.Sku]: [
        'id',
        'sku',
        'isDiscountable',
        'size',
        'note',
        'availability',
        'price',
        'status',
    ],
    [TABLES.Task]: [
        'id',
        'taskId',
        'name',
        'status',
        'description',
        'result',
        'resultCode',
    ],
    [TABLES.Trait]: [
        'id',
        'name',
        'value',
    ],
    [TABLES.Customer]: [
        'id',
        'firstName',
        'lastName',
        'pronouns',
        'theme',
        'lastLoginAttempt',
        'sessionToken',
        'accountApproved',
        'emailVerified',
        'status',
    ]
}