export const StatusCodes = {
    SUCCESS: 100,
    ERROR_UNKNOWN: 200,
    FAILURE_EMAIL_EXISTS: 400,
    FAILURE_NO_USER: 900,
    FAILURE_SOFT_LOCKOUT: 910,
    FAILURE_HARD_LOCKOUT: 920,
    FAILURE_NOT_VERIFIED: 1400,
    ERROR_SOME_IMAGES_ALREADY_UPLOADED: 2500,
}