"""empty message

Revision ID: 4d73c7245825
Revises: 6ab3ccdbb201
Create Date: 2021-01-26 22:07:34.093461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d73c7245825'
down_revision = '6ab3ccdbb201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('display_img_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sku', 'image', ['display_img_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sku', type_='foreignkey')
    op.drop_column('sku', 'display_img_id')
    # ### end Alembic commands ###
