"""empty message

Revision ID: 6ab3ccdbb201
Revises: 
Create Date: 2021-01-26 20:24:03.801652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab3ccdbb201'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('address_user_id_fkey', 'address', type_='foreignkey')
    op.drop_column('address', 'user_id')
    op.add_column('order', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'address', ['address_id'], ['id'])
    op.add_column('phone', sa.Column('extension', sa.String(length=10), nullable=True))
    op.drop_constraint('user_cart_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'cart_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_cart_id_fkey', 'user', 'order', ['cart_id'], ['id'])
    op.drop_column('phone', 'extension')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'address_id')
    op.add_column('address', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('address_user_id_fkey', 'address', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
