"""empty message

Revision ID: 7a16cb2f8e2f
Revises: 4d73c7245825
Create Date: 2021-01-27 00:53:52.761928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a16cb2f8e2f'
down_revision = '4d73c7245825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('size', sa.Column('availability', sa.Integer(), nullable=False))
    op.drop_column('sku', 'availability')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('availability', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('size', 'availability')
    # ### end Alembic commands ###
