"""empty message

Revision ID: 981ec5aa5db9
Revises: 5af486fb9543
Create Date: 2021-02-22 13:11:36.202507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981ec5aa5db9'
down_revision = '5af486fb9543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('display_img_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plant', 'image', ['display_img_id'], ['id'])
    op.drop_constraint('sku_display_img_id_fkey', 'sku', type_='foreignkey')
    op.drop_column('sku', 'display_img_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('display_img_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('sku_display_img_id_fkey', 'sku', 'image', ['display_img_id'], ['id'])
    op.drop_constraint(None, 'plant', type_='foreignkey')
    op.drop_column('plant', 'display_img_id')
    # ### end Alembic commands ###
