"""empty message

Revision ID: 9e3322745499
Revises: 
Create Date: 2021-02-03 17:36:52.168725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3322745499'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('date_added', sa.Float(), nullable=False))
    op.add_column('sku', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sku', 'price')
    op.drop_column('sku', 'date_added')
    # ### end Alembic commands ###
