"""empty message

Revision ID: a97b99bb77c4
Revises: 
Create Date: 2021-03-08 01:45:19.147069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97b99bb77c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('tag', sa.String(length=32), server_default='nenew', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'tag')
    # ### end Alembic commands ###
