"""empty message

Revision ID: bd7561cd04cd
Revises: 
Create Date: 2021-03-07 20:42:10.465436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7561cd04cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('tag', sa.String(length=32), server_default='zckufg0r7FvxJzCpggQEge1TRThFJznE', nullable=False))
    op.create_unique_constraint(None, 'customer', ['tag'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='unique')
    op.drop_column('customer', 'tag')
    # ### end Alembic commands ###
